### ISSUE TITLE
Support using local cache from nix-magic-cache

### ISSUE THREAD

**Issue by ParetoOptimalDev** [srid/nixci#28]
I tried adding this in the flake:

```nix
nixConfig.binaryCaches = [ "http://127.0.0.1:37515/" ];
```

However that doesn't seem to be enough for `nixci` to use the binary cache there that nix-magic-cache creates.

This should also speed up builds since nix-magic-cache puts things in the github filesystem cache.

**Comment by srid** [comment]
`nixci` uses `nix build ...` under the hood, so shouldn't this already work?

**Comment by ParetoOptimalDev** [comment]
That's what I thought. Here is my github actions run:

https://github.com/ParetoOptimalDev/haskell-template2/actions/runs/6163342143/job/16726686449

My expected result was that I see substitutions from `127.0.0.1:37515` and "test build time after first run of..." would be around 2m rather than 4mlike the previous build in the [actions list](https://github.com/ParetoOptimalDev/haskell-template2/actions).

**Comment by srid** [comment]
I'm not too familiar with nix-magic-cache, but with nixci you can also pass nix arguments as follows (after the `--`):

```
nixci -- --extra-substituters 'http://localhost: 37515' --option require-sigs false 
```

Note: this is only available in `master` branch, and not released yet.
